import { type Style } from 'mapbox-gl';

const style: Style = {
  version: 8,
  name: 'IPC Light',
  metadata: {},
  center: [34.41418453301549, 5.880610617754584],
  zoom: 10.381989840638647,
  bearing: 0,
  pitch: 0,
  sources: {
    'mapbox://mapbox.terrain-rgb': {
      url: 'mapbox://mapbox.terrain-rgb',
      type: 'raster-dem',
      tileSize: 256,
    },
    composite: {
      url: 'mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2',
      type: 'vector',
    },
  },
  sprite:
    'mapbox://sprites/axismaps/ck7aiih8f4qgq1intrzddrl8o/58wt9cmgysbhznn6q499o2w9u',
  glyphs: 'mapbox://fonts/axismaps/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'land',
      type: 'background',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, land',
      },
      layout: {},
      paint: { 'background-color': 'hsl(0, 0%, 92%)' },
    },
    {
      id: 'landcover',
      type: 'fill',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, land',
      },
      source: 'composite',
      'source-layer': 'landcover',
      maxzoom: 7,
      layout: {},
      paint: {
        'fill-color': 'hsl(185, 0%, 91%)',
        'fill-opacity': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          2,
          0.3,
          7,
          0,
        ],
        'fill-antialias': false,
      },
    },
    {
      id: 'national-park',
      type: 'fill',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, land',
      },
      source: 'composite',
      'source-layer': 'landuse_overlay',
      minzoom: 5,
      filter: ['==', ['get', 'class'], 'national_park'],
      layout: {},
      paint: {
        'fill-color': 'hsl(185, 2%, 89%)',
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0,
          6,
          0.5,
          10,
          0.5,
        ],
      },
    },
    {
      id: 'landuse',
      type: 'fill',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, land',
      },
      source: 'composite',
      'source-layer': 'landuse',
      minzoom: 5,
      filter: [
        'match',
        ['get', 'class'],
        ['park', 'airport', 'glacier', 'pitch', 'sand'],
        true,
        false,
      ],
      layout: {},
      paint: {
        'fill-color': 'hsl(185, 2%, 89%)',
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0,
          6,
          ['match', ['get', 'class'], 'glacier', 0.5, 1],
        ],
      },
    },
    {
      id: 'land-structure-polygon',
      type: 'fill',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, built',
      },
      source: 'composite',
      'source-layer': 'structure',
      minzoom: 13,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'land'],
      ],
      layout: {},
      paint: { 'fill-color': 'hsl(185, 0%, 94%)' },
    },
    {
      id: 'land-structure-line',
      type: 'line',
      metadata: {
        'mapbox:featureComponent': 'land-and-water',
        'mapbox:group': 'Land & water, built',
      },
      source: 'composite',
      'source-layer': 'structure',
      minzoom: 13,
      filter: [
        'all',
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'land'],
      ],
      layout: { 'line-cap': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.99],
          ['zoom'],
          14,
          0.75,
          20,
          40,
        ],
        'line-color': 'hsl(185, 0%, 94%)',
      },
    },
    {
      id: 'waterway-shadow',
      type: 'line',
      metadata: { 'mapbox:group': 'a4ce6228380cedb1353181fdc3c626f2' },
      source: 'composite',
      'source-layer': 'waterway',
      minzoom: 8,
      layout: {
        'line-cap': ['step', ['zoom'], 'butt', 11, 'round'],
        'line-join': 'round',
      },
      paint: {
        'line-color': 'hsl(212, 47%, 63%)',
        'line-width': [
          'interpolate',
          ['exponential', 1.3],
          ['zoom'],
          9,
          ['match', ['get', 'class'], ['canal', 'river'], 0.1, 0],
          20,
          ['match', ['get', 'class'], ['canal', 'river'], 8, 3],
        ],
        'line-translate': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          7,
          ['literal', [0, 0]],
          16,
          ['literal', [-1, -1]],
        ],
        'line-translate-anchor': 'viewport',
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0, 8.5, 1],
      },
    },
    {
      id: 'water-shadow copy',
      type: 'fill',
      metadata: { 'mapbox:group': 'a4ce6228380cedb1353181fdc3c626f2' },
      source: 'composite',
      'source-layer': 'water',
      layout: {},
      paint: {
        'fill-color': 'hsl(212, 25%, 73%)',
        'fill-translate-anchor': 'viewport',
      },
    },
    {
      id: 'waterway copy',
      type: 'line',
      metadata: { 'mapbox:group': 'a4ce6228380cedb1353181fdc3c626f2' },
      source: 'composite',
      'source-layer': 'waterway',
      minzoom: 8,
      layout: {
        'line-cap': ['step', ['zoom'], 'butt', 11, 'round'],
        'line-join': 'round',
      },
      paint: {
        'line-color': '#91b7e1',
        'line-width': [
          'interpolate',
          ['exponential', 1.3],
          ['zoom'],
          9,
          ['match', ['get', 'class'], ['canal', 'river'], 0.1, 0],
          20,
          ['match', ['get', 'class'], ['canal', 'river'], 8, 3],
        ],
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 8, 0, 8.5, 1],
      },
    },
    {
      id: 'water copy',
      type: 'fill',
      metadata: { 'mapbox:group': 'a4ce6228380cedb1353181fdc3c626f2' },
      source: 'composite',
      'source-layer': 'water',
      layout: {},
      paint: { 'fill-color': 'hsl(212, 35%, 73%)' },
    },
    {
      id: 'admin-0-boundary-bg copy',
      type: 'line',
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 3.5, 10, 8],
        'line-color': 'hsl(185, 0%, 30%)',
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 4, 0, 5, 0.2],
        'line-translate': [0, 0],
      },
    },
    {
      id: 'water border',
      type: 'line',
      metadata: { 'mapbox:group': 'a4ce6228380cedb1353181fdc3c626f2' },
      source: 'composite',
      'source-layer': 'water',
      layout: {},
      paint: {
        'line-color': 'hsl(211, 45%, 60%)',
        'line-width': 1,
      },
    },
    {
      id: 'admin-0-boundary copy',
      type: 'line',
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'disputed'], 'false'],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': 'hsl(185, 0%, 30%)',
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 10, 2],
        'line-dasharray': [10, 0],
      },
    },
    {
      id: 'admin-0-boundary-disputed copy',
      type: 'line',
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'disputed'], 'true'],
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': 'hsl(185, 0%, 30%)',
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          4,
          0.75,
          8,
          2,
        ],
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [3.25, 3.25]],
          6,
          ['literal', [2.5, 2.5]],
          7,
          ['literal', [2, 2.25]],
          8,
          ['literal', [1.75, 2]],
        ],
      },
    },
    {
      id: 'mapbox-terrain-rgb',
      type: 'hillshade',
      source: 'mapbox://mapbox.terrain-rgb',
      layout: {},
      paint: {
        'hillshade-shadow-color': 'hsl(0, 0%, 0%)',
        'hillshade-exaggeration': 0.2,
        'hillshade-accent-color': 'hsl(0, 0%, 0%)',
        'hillshade-highlight-color': 'hsl(0, 0%, 100%)',
      },
    },
    {
      id: 'waterway-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'natural-features',
        'mapbox:group': 'Natural features, natural-labels',
      },
      source: 'composite',
      'source-layer': 'natural_label',
      minzoom: 13,
      filter: [
        'all',
        ['match', ['get', 'class'], ['canal', 'river', 'stream'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: {
        'text-font': ['Myriad Pro Italic', 'Arial Unicode MS Regular'],
        'text-max-angle': 30,
        'symbol-spacing': [
          'interpolate',
          ['linear', 1],
          ['zoom'],
          15,
          250,
          17,
          400,
        ],
        'text-size': ['interpolate', ['linear'], ['zoom'], 13, 12, 18, 16],
        'symbol-placement': 'line',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      },
      paint: { 'text-color': 'hsl(185, 0%, 55%)' },
    },
    {
      id: 'water-line-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'natural-features',
        'mapbox:group': 'Natural features, natural-labels',
      },
      source: 'composite',
      'source-layer': 'natural_label',
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['bay', 'ocean', 'reservoir', 'sea', 'water'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: {
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          ['step', ['get', 'sizerank'], 24, 6, 18, 12, 12],
          10,
          ['step', ['get', 'sizerank'], 18, 9, 12],
          18,
          ['step', ['get', 'sizerank'], 18, 9, 16],
        ],
        'text-max-angle': 30,
        'text-letter-spacing': [
          'match',
          ['get', 'class'],
          'ocean',
          0.25,
          ['sea', 'bay'],
          0.15,
          0,
        ],
        'text-font': ['Myriad Pro Italic', 'Arial Unicode MS Regular'],
        'symbol-placement': 'line-center',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      },
      paint: { 'text-color': '#666' },
    },
    {
      id: 'water-point-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'natural-features',
        'mapbox:group': 'Natural features, natural-labels',
      },
      source: 'composite',
      'source-layer': 'natural_label',
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['bay', 'ocean', 'reservoir', 'sea', 'water'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'Point'],
      ],
      layout: {
        'text-line-height': 1.3,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          ['step', ['get', 'sizerank'], 24, 6, 18, 12, 12],
          10,
          ['step', ['get', 'sizerank'], 18, 9, 12],
        ],
        'text-font': ['Myriad Pro Italic', 'Arial Unicode MS Regular'],
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-letter-spacing': [
          'match',
          ['get', 'class'],
          'ocean',
          0.25,
          ['bay', 'sea'],
          0.15,
          0.01,
        ],
        'text-max-width': [
          'match',
          ['get', 'class'],
          'ocean',
          4,
          'sea',
          5,
          ['bay', 'water'],
          7,
          10,
        ],
      },
      paint: { 'text-color': '#666' },
    },
    {
      id: 'settlement-subdivision-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'place-labels',
        'mapbox:group': 'Place labels, place-labels',
      },
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 10,
      maxzoom: 15,
      filter: [
        'all',
        ['==', ['get', 'class'], 'settlement_subdivision'],
        ['<=', ['get', 'filterrank'], 4],
      ],
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-transform': 'uppercase',
        'text-font': ['DIN Pro Regular', 'Arial Unicode MS Regular'],
        'text-letter-spacing': ['match', ['get', 'type'], 'suburb', 0.15, 0.1],
        'text-max-width': 7,
        'text-padding': 3,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.5, 0, 1, 1],
          ['zoom'],
          11,
          ['match', ['get', 'type'], 'suburb', 11, 10.5],
          15,
          ['match', ['get', 'type'], 'suburb', 17, 16],
        ],
      },
      paint: {
        'text-halo-color': 'hsl(185, 0%, 100%)',
        'text-halo-width': 1,
        'text-color': 'hsl(0, 0%, 10%)',
      },
    },
    {
      id: 'settlement-minor-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'place-labels',
        'mapbox:group': 'Place labels, place-labels',
      },
      source: 'composite',
      'source-layer': 'place_label',
      maxzoom: 15,
      minzoom: 5,
      filter: [
        'all',
        ['<=', ['get', 'filterrank'], 3],
        ['==', ['get', 'class'], 'settlement'],
        [
          'step',
          ['zoom'],
          true,
          8,
          ['>=', ['get', 'symbolrank'], 11],
          10,
          ['>=', ['get', 'symbolrank'], 12],
          11,
          ['>=', ['get', 'symbolrank'], 13],
          12,
          ['>=', ['get', 'symbolrank'], 15],
          13,
          ['>=', ['get', 'symbolrank'], 11],
          14,
          ['>=', ['get', 'symbolrank'], 13],
        ],
      ],
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.2, 0, 0.9, 1],
          ['zoom'],
          5,
          9,
          13,
          [
            'step',
            ['get', 'symbolrank'],
            25,
            9,
            23,
            9.5,
            21,
            10,
            19,
            11,
            18,
            12,
            17,
            13,
            15,
          ],
        ],
        'icon-image': [
          'step',
          ['zoom'],
          [
            'case',
            ['==', ['get', 'capital'], 2],
            'border-dot-13',
            ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
          ],
          8,
          '',
        ],
        'text-font': ['Myriad Pro Regular', 'Arial Unicode MS Regular'],
        'text-justify': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            ['left', 'bottom-left', 'top-left'],
            'left',
            ['right', 'bottom-right', 'top-right'],
            'right',
            'center',
          ],
          8,
          'center',
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'capital'],
            2,
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.3]],
              'bottom-left',
              ['literal', [0.3, -0.1]],
              'left',
              ['literal', [0.45, 0.1]],
              'top-left',
              ['literal', [0.3, 0.1]],
              'top',
              ['literal', [0, 0.3]],
              'top-right',
              ['literal', [-0.3, 0.1]],
              'right',
              ['literal', [-0.45, 0]],
              'bottom-right',
              ['literal', [-0.3, -0.1]],
              ['literal', [0, -0.3]],
            ],
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.25]],
              'bottom-left',
              ['literal', [0.2, -0.05]],
              'left',
              ['literal', [0.4, 0.05]],
              'top-left',
              ['literal', [0.2, 0.05]],
              'top',
              ['literal', [0, 0.25]],
              'top-right',
              ['literal', [-0.2, 0.05]],
              'right',
              ['literal', [-0.4, 0.05]],
              'bottom-right',
              ['literal', [-0.2, -0.05]],
              ['literal', [0, -0.25]],
            ],
          ],
          8,
          ['literal', [0, 0]],
        ],
        'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-letter-spacing': 0.03,
        'text-max-width': 7,
      },
      paint: {
        'text-color': 'hsl(0, 0%, 10%)',
        'text-halo-color': 'hsl(185, 0%, 100%)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'settlement-major-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'place-labels',
        'mapbox:group': 'Place labels, place-labels',
      },
      source: 'composite',
      'source-layer': 'place_label',
      maxzoom: 15,
      filter: [
        'all',
        ['<=', ['get', 'filterrank'], 3],
        ['==', ['get', 'class'], 'settlement'],
        [
          'step',
          ['zoom'],
          false,
          8,
          ['<', ['get', 'symbolrank'], 11],
          10,
          ['<', ['get', 'symbolrank'], 12],
          11,
          ['<', ['get', 'symbolrank'], 13],
          12,
          ['<', ['get', 'symbolrank'], 15],
          13,
          ['>=', ['get', 'symbolrank'], 11],
          14,
          ['>=', ['get', 'symbolrank'], 13],
        ],
      ],
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.2, 0, 0.9, 1],
          ['zoom'],
          8,
          9,
          15,
          [
            'step',
            ['get', 'symbolrank'],
            28,
            9,
            26,
            9.5,
            23,
            10,
            21,
            11,
            20,
            12,
            19,
            13,
            16,
          ],
        ],
        'icon-image': [
          'step',
          ['zoom'],
          [
            'case',
            ['==', ['get', 'capital'], 2],
            'border-dot-13',
            ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
          ],
          8,
          '',
        ],
        'text-font': ['Myriad Pro Semibold', 'Arial Unicode MS Regular'],
        'text-justify': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            ['left', 'bottom-left', 'top-left'],
            'left',
            ['right', 'bottom-right', 'top-right'],
            'right',
            'center',
          ],
          8,
          'center',
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'capital'],
            2,
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.3]],
              'bottom-left',
              ['literal', [0.3, -0.1]],
              'left',
              ['literal', [0.45, 0.1]],
              'top-left',
              ['literal', [0.3, 0.1]],
              'top',
              ['literal', [0, 0.3]],
              'top-right',
              ['literal', [-0.3, 0.1]],
              'right',
              ['literal', [-0.45, 0]],
              'bottom-right',
              ['literal', [-0.3, -0.1]],
              ['literal', [0, -0.3]],
            ],
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.25]],
              'bottom-left',
              ['literal', [0.2, -0.05]],
              'left',
              ['literal', [0.4, 0.05]],
              'top-left',
              ['literal', [0.2, 0.05]],
              'top',
              ['literal', [0, 0.25]],
              'top-right',
              ['literal', [-0.2, 0.05]],
              'right',
              ['literal', [-0.4, 0.05]],
              'bottom-right',
              ['literal', [-0.2, -0.05]],
              ['literal', [0, -0.25]],
            ],
          ],
          8,
          ['literal', [0, 0]],
        ],
        'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-max-width': 7,
      },
      paint: {
        'text-color': [
          'step',
          ['get', 'symbolrank'],
          '#000000',
          11,
          'hsl(0, 0%, 20%)',
          16,
          'hsl(185, 0%, 40%)',
        ],
        'text-halo-color': 'hsl(185, 0%, 100%)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'state-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'place-labels',
        'mapbox:group': 'Place labels, place-labels',
      },
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 3,
      maxzoom: 9,
      filter: ['==', ['get', 'class'], 'state'],
      layout: {
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.85, 0.7, 0.65, 1],
          ['zoom'],
          4,
          ['step', ['get', 'symbolrank'], 10, 6, 9.5, 7, 9],
          9,
          ['step', ['get', 'symbolrank'], 24, 6, 18, 7, 14],
        ],
        'text-transform': 'uppercase',
        'text-font': ['DIN Pro Bold', 'Arial Unicode MS Bold'],
        'text-field': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'symbolrank'],
            ['coalesce', ['get', 'name_en'], ['get', 'name']],
            5,
            ['coalesce', ['get', 'abbr'], ['get', 'name_en'], ['get', 'name']],
          ],
          5,
          ['coalesce', ['get', 'name_en'], ['get', 'name']],
        ],
        'text-letter-spacing': 0.15,
        'text-max-width': 6,
      },
      paint: {
        'text-color': 'hsl(0, 0%, 10%)',
        'text-halo-color': 'hsl(185, 0%, 100%)',
        'text-halo-width': 1,
      },
    },
    {
      id: 'country-label',
      type: 'symbol',
      metadata: {
        'mapbox:featureComponent': 'place-labels',
        'mapbox:group': 'Place labels, place-labels',
      },
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 1,
      maxzoom: 10,
      filter: ['==', ['get', 'class'], 'country'],
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.2, 0, 0.7, 1],
          ['zoom'],
          1,
          ['step', ['get', 'symbolrank'], 11, 4, 9, 5, 8],
          9,
          ['step', ['get', 'symbolrank'], 28, 4, 22, 5, 21],
        ],
        'icon-image': '',
        'text-transform': 'uppercase',
        'text-font': ['Myriad Pro Semibold', 'Arial Unicode MS Regular'],
        'text-justify': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            ['left', 'bottom-left', 'top-left'],
            'left',
            ['right', 'bottom-right', 'top-right'],
            'right',
            'center',
          ],
          7,
          'center',
        ],
        'text-offset': ['literal', [0, 0]],
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          4,
          0.1,
          6,
          0.3,
          7,
          0.5,
        ],
        'text-max-width': 6,
      },
      paint: {
        'icon-opacity': [
          'step',
          ['zoom'],
          ['case', ['has', 'text_anchor'], 1, 0],
          7,
          0,
        ],
        'text-color': 'hsl(0, 0%, 10%)',
        'text-halo-color': 'hsl(185, 0%, 100%)',
        'text-halo-width': 1.25,
      },
    },
  ],
};

export default style;
